# Generated by Django 3.0.14 on 2023-10-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime')], default='Fulltime', max_length=50),
        ),
    ]
