# Generated by Django 3.0.14 on 2023-10-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime')], default='', max_length=50),
        ),
    ]
